spring.application.name=voltera

spring.datasource.url=jdbc:postgresql://localhost:5432/voltera
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
jwt.refresh-expiration=86400000

# AWS Credentials

cloudflare.r2.access-key-id=${R2_ACCESS_KEY}
cloudflare.r2.secret-key-id=${R2_SECRET_KEY}
cloudflare.r2.account-id=${R2_ACCOUNT_ID}
cloudflare.r2.end-point=${R2_END_POINT}
cloudflare.r2.bucket-name=${R2_BUCKET_NAME}
cloudflare.r2.public-base-url=${R2_PUBLIC_BASE_URL}


# Redis Cloud (Upstash)
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=false


# EMAIL (SMTP Gmail)
spring.mail.host=${SMTP_HOST}
spring.mail.port=587
spring.mail.username=${SMTP_MAIL_USERNAME}
spring.mail.password=${SMTP_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#  GOOGLE OAUTH2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_SCOPE}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}
spring.security.oauth2.client.provider.google.authorization-uri=${GOOGLE_AUTH_URL}
spring.security.oauth2.client.provider.google.token-uri=${GOOGLE_TOKEN_URL}
spring.security.oauth2.client.provider.google.user-info-uri=${GOOGLE_USERINFO_URL}

# PAYOS
payos.client-id=${PAYOS_CLIENT_ID}
payos.api-key=${PAYOS_API_KEY}
payos.checksum-key=${PAYOS_CHECKSUM_KEY}

#vnp config
vnpay.vnp-pay-url=${VNP_URL}
vnpay.vnp-return-url=${VNP_RETURN_URL}
vnpay.vnp-tmn-code=${VNP_TMN_CODE}
vnpay.vnp-hash-secret=${VNP_HASH_SECRET_KEY}
vnpay.vnp-api-url=${VNP_API_URL}
vnpay.vnp-version=2.1.0

logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG