-- PostgreSQL schema generated from `com.g_wuy.swp391.voltera.entity`
-- Column names normalized to snake_case

DROP TABLE IF EXISTS bank_transfer CASCADE;
DROP TABLE IF EXISTS refund CASCADE;
DROP TABLE IF EXISTS complaint_reply CASCADE;
DROP TABLE IF EXISTS refund_image CASCADE;
DROP TABLE IF EXISTS complaint_image CASCADE;
DROP TABLE IF EXISTS vehicle_image CASCADE;
DROP TABLE IF EXISTS battery_image CASCADE;
DROP TABLE IF EXISTS favorite_list CASCADE;
DROP TABLE IF EXISTS feedback CASCADE;
DROP TABLE IF EXISTS fee CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS notification CASCADE;
DROP TABLE IF EXISTS battery CASCADE;
DROP TABLE IF EXISTS vehicle CASCADE;
DROP TABLE IF EXISTS complaint CASCADE;
DROP TABLE IF EXISTS "transaction" CASCADE;
DROP TABLE IF EXISTS contract CASCADE;
DROP TABLE IF EXISTS report CASCADE;
DROP TABLE IF EXISTS review CASCADE;
DROP TABLE IF EXISTS bank CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS battery_type CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

CREATE TABLE "user" (
    user_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(100),
    last_name       VARCHAR(100),
    full_name       VARCHAR(200),
    email           VARCHAR(150),
    phone           VARCHAR(20),
    gender          BOOLEAN,
    address         TEXT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    avatar          TEXT,
    email_verified  BOOLEAN
);

CREATE TABLE battery_type (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name       VARCHAR(100) NOT NULL,
    technical       VARCHAR(200),
    description     TEXT
);

CREATE TABLE report (
    report_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    month              INTEGER,
    year               INTEGER,
    total_revenue      NUMERIC(12,2),
    total_transactions BIGINT,
    updated_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE post (
    post_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id      INTEGER,
    title          VARCHAR(200),
    description    TEXT,
    price          NUMERIC(12,2),
    status         VARCHAR(20) DEFAULT 'PENDING',
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contract (
    contract_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id          INTEGER,
    seller_id        INTEGER,
    buyer_id         INTEGER,
    contract_file    TEXT,
    contract_status  VARCHAR(20) DEFAULT 'PENDING',
    signed_date      DATE,
    expiration_date  DATE,
    seller_signed    BOOLEAN,
    buyer_signed     BOOLEAN,
    terms            TEXT
);

CREATE TABLE complaint (
    complaint_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id       INTEGER,
    problem         VARCHAR(200),
    description     TEXT,
    status          VARCHAR(20) DEFAULT 'PENDING',
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    resolved_at     TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE review (
    review_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    writer_id    INTEGER,
    content      TEXT,
    rating       INTEGER
);

CREATE TABLE account (
    user_id        INTEGER PRIMARY KEY,
    username       VARCHAR(100) NOT NULL,
    password       VARCHAR(255) NOT NULL,
    role           VARCHAR(20),
    status         VARCHAR(20) DEFAULT 'PENDING',
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    refresh_token  VARCHAR(1000)
);

CREATE TABLE bank (
    bank_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL,
    bank_name       VARCHAR(150) NOT NULL,
    account_number  VARCHAR(50) NOT NULL,
    account_name    VARCHAR(200) NOT NULL,
    security_code   INTEGER,
    exp_date        DATE,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status          VARCHAR(20),
    balance         NUMERIC(12,2) DEFAULT 0
);

CREATE TABLE vehicle (
    post_id            INTEGER PRIMARY KEY,
    brand              VARCHAR(100),
    model              VARCHAR(100),
    version            VARCHAR(50),
    odo                INTEGER,
    battery_capacity   NUMERIC(10,2),
    range              INTEGER,
    charging_time      INTEGER,
    color              VARCHAR(50),
    number_of_seat     INTEGER,
    style              VARCHAR(50),
    body_insurance     BOOLEAN DEFAULT FALSE,
    vehicle_inspection  BOOLEAN DEFAULT FALSE,
    license_plate      VARCHAR(8),
    origin             VARCHAR(255),
    status             VARCHAR(20),
    year_manufacture   INTEGER NOT NULL
);

CREATE TABLE battery (
    post_id             INTEGER PRIMARY KEY,
    battery_type_id     INTEGER,
    serial_number       VARCHAR(100) NOT NULL,
    origin_capacity     NUMERIC(10,2),
    remaining_capacity  NUMERIC(10,2),
    mileage_covered     INTEGER,
    voltage             NUMERIC(10,2),
    cycle_count         INTEGER,
    warranty            VARCHAR(100),
    weight              NUMERIC(10,2),
    lifecycle           VARCHAR(100),
    status              VARCHAR(20) DEFAULT 'AVAILABLE'
);

CREATE TABLE notification (
    notification_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          INTEGER NOT NULL,
    title            VARCHAR(255) NOT NULL,
    message          VARCHAR(500) NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_status      BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE "transaction" (
    transaction_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id             INTEGER NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE,
    price               NUMERIC(12,2),
    contract_id         INTEGER,
    report_id           INTEGER,
    transaction_status  VARCHAR(20) DEFAULT 'PENDING',
    buyer_id            INTEGER
);

CREATE TABLE payment (
    payment_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id       INTEGER,
    payment_method       VARCHAR(50),
    payment_status       VARCHAR(20),
    transaction_code     VARCHAR(100),
    payment_date         TIMESTAMP WITHOUT TIME ZONE,
    vnp_transaction_no   VARCHAR(100),
    vnp_bank_code        VARCHAR(20),
    vnp_bank_tran_no     VARCHAR(255),
    vnp_card_type        VARCHAR(20),
    vnp_pay_date         VARCHAR(14),
    vnp_response_code    VARCHAR(2),
    amount               NUMERIC(12,2),
    order_info           VARCHAR(255),
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE fee (
    fee_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id         INTEGER,
    amount          NUMERIC(12,2),
    description     TEXT,
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    expired_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fee_status      VARCHAR(255),
    transaction_id  INTEGER
);

CREATE TABLE feedback (
    feedback_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id INTEGER,
    rating         INTEGER,
    comment        TEXT,
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE favorite_list (
    favorite_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER NOT NULL,
    post_id       INTEGER NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE battery_image (
    image_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id       INTEGER,
    image_url     TEXT NOT NULL,
    uploaded_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vehicle_image (
    image_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id       INTEGER,
    image_url     TEXT NOT NULL,
    uploaded_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE complaint_image (
    image_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id  INTEGER,
    image_url     TEXT NOT NULL,
    uploaded_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE complaint_reply (
    reply_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id  INTEGER,
    sender_id     INTEGER,
    message       TEXT NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    receiver_id   INTEGER,
    resolved_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refund (
    refund_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id INTEGER,
    sender_id      INTEGER,
    receiver_id    INTEGER,
    amount         NUMERIC(12,2) NOT NULL,
    reason         TEXT,
    refund_status  VARCHAR(20) DEFAULT 'REQUESTED',
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    claimed_at     TIMESTAMP WITH TIME ZONE
);

CREATE TABLE refund_image (
    image_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id     INTEGER NOT NULL,
    image_url     TEXT NOT NULL,
    uploaded_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bank_transfer (
    transfer_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id       INTEGER,
    transaction_id   INTEGER,
    seller_id        INTEGER,
    bank_id          INTEGER,
    amount           NUMERIC(12,2) NOT NULL,
    transfer_status  VARCHAR(20) DEFAULT 'PENDING',
    initiated_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    completed_at     TIMESTAMP WITH TIME ZONE,
    description      TEXT
);

ALTER TABLE post
    ADD CONSTRAINT fk_post_user
    FOREIGN KEY (seller_id) REFERENCES "user" (user_id);

ALTER TABLE contract
    ADD CONSTRAINT fk_contract_post
    FOREIGN KEY (post_id) REFERENCES post (post_id),
    ADD CONSTRAINT fk_contract_seller
    FOREIGN KEY (seller_id) REFERENCES "user" (user_id),
    ADD CONSTRAINT fk_contract_buyer
    FOREIGN KEY (buyer_id) REFERENCES "user" (user_id);

ALTER TABLE complaint
    ADD CONSTRAINT fk_complaint_sender
    FOREIGN KEY (sender_id) REFERENCES "user" (user_id);

ALTER TABLE review
    ADD CONSTRAINT fk_review_writer
    FOREIGN KEY (writer_id) REFERENCES "user" (user_id);

ALTER TABLE account
    ADD CONSTRAINT fk_account_user
    FOREIGN KEY (user_id) REFERENCES "user" (user_id);

ALTER TABLE bank
    ADD CONSTRAINT fk_bank_user
    FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE CASCADE;

ALTER TABLE vehicle
    ADD CONSTRAINT fk_vehicle_post
    FOREIGN KEY (post_id) REFERENCES post (post_id) ON DELETE CASCADE;

ALTER TABLE battery
    ADD CONSTRAINT fk_battery_post
    FOREIGN KEY (post_id) REFERENCES post (post_id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_battery_type
    FOREIGN KEY (battery_type_id) REFERENCES battery_type (id);

ALTER TABLE notification
    ADD CONSTRAINT fk_notification_user
    FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE CASCADE;

ALTER TABLE "transaction"
    ADD CONSTRAINT fk_transaction_post
    FOREIGN KEY (post_id) REFERENCES post (post_id),
    ADD CONSTRAINT fk_transaction_contract
    FOREIGN KEY (contract_id) REFERENCES contract (contract_id),
    ADD CONSTRAINT fk_transaction_report
    FOREIGN KEY (report_id) REFERENCES report (report_id),
    ADD CONSTRAINT fk_transaction_buyer
    FOREIGN KEY (buyer_id) REFERENCES "user" (user_id);

ALTER TABLE payment
    ADD CONSTRAINT fk_payment_transaction
    FOREIGN KEY (transaction_id) REFERENCES "transaction" (transaction_id);

ALTER TABLE fee
    ADD CONSTRAINT fk_fee_post
    FOREIGN KEY (post_id) REFERENCES post (post_id),
    ADD CONSTRAINT fk_fee_transaction
    FOREIGN KEY (transaction_id) REFERENCES "transaction" (transaction_id);

ALTER TABLE feedback
    ADD CONSTRAINT fk_feedback_transaction
    FOREIGN KEY (transaction_id) REFERENCES "transaction" (transaction_id);

ALTER TABLE favorite_list
    ADD CONSTRAINT fk_favorite_user
    FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_favorite_post
    FOREIGN KEY (post_id) REFERENCES post (post_id) ON DELETE CASCADE;

ALTER TABLE battery_image
    ADD CONSTRAINT fk_battery_image_battery
    FOREIGN KEY (post_id) REFERENCES battery (post_id) ON DELETE CASCADE;

ALTER TABLE vehicle_image
    ADD CONSTRAINT fk_vehicle_image_vehicle
    FOREIGN KEY (post_id) REFERENCES vehicle (post_id) ON DELETE CASCADE;

ALTER TABLE complaint_image
    ADD CONSTRAINT fk_complaint_image_complaint
    FOREIGN KEY (complaint_id) REFERENCES complaint (complaint_id) ON DELETE CASCADE;

ALTER TABLE complaint_reply
    ADD CONSTRAINT fk_complaint_reply_complaint
    FOREIGN KEY (complaint_id) REFERENCES complaint (complaint_id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_complaint_reply_sender
    FOREIGN KEY (sender_id) REFERENCES "user" (user_id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_complaint_reply_receiver
    FOREIGN KEY (receiver_id) REFERENCES "user" (user_id) ON DELETE SET NULL;

ALTER TABLE refund
    ADD CONSTRAINT fk_refund_transaction
    FOREIGN KEY (transaction_id) REFERENCES "transaction" (transaction_id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_refund_sender
    FOREIGN KEY (sender_id) REFERENCES "user" (user_id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_refund_receiver
    FOREIGN KEY (receiver_id) REFERENCES "user" (user_id) ON DELETE SET NULL;

ALTER TABLE refund_image
    ADD CONSTRAINT fk_refund_image_refund
    FOREIGN KEY (refund_id) REFERENCES refund (refund_id) ON DELETE CASCADE;

ALTER TABLE bank_transfer
    ADD CONSTRAINT fk_bank_transfer_payment
    FOREIGN KEY (payment_id) REFERENCES payment (payment_id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_bank_transfer_transaction
    FOREIGN KEY (transaction_id) REFERENCES "transaction" (transaction_id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_bank_transfer_seller
    FOREIGN KEY (seller_id) REFERENCES "user" (user_id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_bank_transfer_bank
    FOREIGN KEY (bank_id) REFERENCES bank (bank_id) ON DELETE SET NULL;
